-- MySQL Script generated by MySQL Workbench
-- Sat May 11 04:54:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chessdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chessdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chessdb` DEFAULT CHARACTER SET utf8 ;
USE `chessdb` ;

-- -----------------------------------------------------
-- Table `chessdb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Country` (
  `idCountry` INT NULL AUTO_INCREMENT,
  `Country` VARCHAR(20) NOT NULL DEFAULT '****',
  PRIMARY KEY (`idCountry`),
  UNIQUE INDEX `CountryName_UNIQUE` (`Country` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Platform` (
  `idPlatform` INT NULL AUTO_INCREMENT,
  `Domain` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPlatform`),
  UNIQUE INDEX `Domain_UNIQUE` (`Domain` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Tactics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Tactics` (
  `idTactics` INT NULL AUTO_INCREMENT,
  `Tactics` VARCHAR(20) NOT NULL DEFAULT 'CHECK (Tactics  != \'\')',
  PRIMARY KEY (`idTactics`),
  UNIQUE INDEX `TrickName_UNIQUE` (`Tactics` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`User` (
  `NickName` VARCHAR(20) NULL DEFAULT 'CHECK (NickName !=  \'\')',
  `Name` VARCHAR(20) NULL DEFAULT 'CHECK (Name !=  \'\')',
  `LastName` VARCHAR(20) NULL DEFAULT 'CHECK (LastName !=  \'\')',
  `CurrentRating` INT NOT NULL DEFAULT CHECK (CurrentRating > 0),
  `idCountry` INT NULL,
  `idPlatform` INT NOT NULL,
  `Rank` ENUM('CM', 'FM', 'IM', 'GM') NULL,
  PRIMARY KEY (`NickName`, `idPlatform`),
  INDEX `fk_User_Country1_idx` (`idCountry` ASC) VISIBLE,
  INDEX `fk_User_Platform1_idx` (`idPlatform` ASC) VISIBLE,
  CONSTRAINT `fk_User_Country1`
    FOREIGN KEY (`idCountry`)
    REFERENCES `chessdb`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Platform1`
    FOREIGN KEY (`idPlatform`)
    REFERENCES `chessdb`.`Platform` (`idPlatform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Opening`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Opening` (
  `idOpening` INT NULL AUTO_INCREMENT,
  `Opening` VARCHAR(20) NOT NULL DEFAULT 'CHECK (Opening != \'\')',
  PRIMARY KEY (`idOpening`),
  UNIQUE INDEX `OpeningName_UNIQUE` (`Opening` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Game` (
  `idGame` INT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Result` ENUM('1:0', '0:1', '1/2:1/2') NOT NULL,
  `MoveCount` INT UNSIGNED NOT NULL DEFAULT CHECK (MoveCount > 0),
  `StartTime` TIME NOT NULL DEFAULT CHECK (StartTime > CAST('00:00:00' AS TIME)),
  `SecondToAdd` INT UNSIGNED NOT NULL,
  `idOpening` INT NOT NULL,
  `idPlatform` INT NOT NULL,
  `Path` VARCHAR(20) NOT NULL DEFAULT '*******',
  PRIMARY KEY (`idGame`),
  INDEX `fk_Game_Opening1_idx` (`idOpening` ASC) VISIBLE,
  INDEX `fk_Game_Platform1_idx` (`idPlatform` ASC) VISIBLE,
  CONSTRAINT `fk_Game_Opening1`
    FOREIGN KEY (`idOpening`)
    REFERENCES `chessdb`.`Opening` (`idOpening`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_Platform1`
    FOREIGN KEY (`idPlatform`)
    REFERENCES `chessdb`.`Platform` (`idPlatform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`User_Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`User_Game` (
  `idGame` INT NOT NULL,
  `Color` ENUM('White', 'Black') NOT NULL,
  `Rating` INT NOT NULL DEFAULT CHECK (Rating > 0),
  `NickName` VARCHAR(20) NOT NULL,
  `idPlatform` INT NOT NULL,
  `idUser_Game` INT NULL AUTO_INCREMENT,
  INDEX `fk_User_has_Game_Game1_idx` (`idGame` ASC) VISIBLE,
  INDEX `fk_User_Game_User1_idx` (`NickName` ASC, `idPlatform` ASC) VISIBLE,
  PRIMARY KEY (`idUser_Game`),
  CONSTRAINT `fk_User_has_Game_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `chessdb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Game_User1`
    FOREIGN KEY (`NickName` , `idPlatform`)
    REFERENCES `chessdb`.`User` (`NickName` , `idPlatform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Sequence` (
  `idSequence` INT NULL AUTO_INCREMENT,
  `SequenceLength` INT NOT NULL,
  `idUser_Game` INT NOT NULL,
  `NumberStartMove` INT NOT NULL,
  `Count` INT NOT NULL,
  `idTactics` INT NOT NULL,
  PRIMARY KEY (`idSequence`),
  INDEX `fk_Sequence_User_Game1_idx` (`idUser_Game` ASC) VISIBLE,
  INDEX `fk_Sequence_Tactics1_idx` (`idTactics` ASC) VISIBLE,
  CONSTRAINT `fk_Sequence_User_Game1`
    FOREIGN KEY (`idUser_Game`)
    REFERENCES `chessdb`.`User_Game` (`idUser_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sequence_Tactics1`
    FOREIGN KEY (`idTactics`)
    REFERENCES `chessdb`.`Tactics` (`idTactics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
