-- MySQL Script generated by MySQL Workbench
-- Sun May 12 16:23:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chessdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chessdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chessdb` DEFAULT CHARACTER SET utf8 ;
USE `chessdb` ;

-- -----------------------------------------------------
-- Table `chessdb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Country` (
  `idCountry` INT AUTO_INCREMENT,
  `Country` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCountry`),
  UNIQUE INDEX `Country_UNIQUE` (`Country` ASC),
  CONSTRAINT `Country_empty` CHECK (`Country` != ''))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Platform` (
  `idPlatform` INT AUTO_INCREMENT,
  `Domain` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPlatform`),
  UNIQUE INDEX `Domain_UNIQUE` (`Domain` ASC),
  CONSTRAINT `Domain_empty` CHECK (`Domain` != ''),
  CONSTRAINT `Domain_regexp` CHECK (REGEXP_LIKE(`Domain`, '^[0-9A-Za-z-]+$')))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Tactics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Tactics` (
  `idTactics` INT AUTO_INCREMENT,
  `Tactics` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTactics`),
  UNIQUE INDEX `Tactics_UNIQUE` (`Tactics` ASC),
  CONSTRAINT `Tactics_empty` CHECK (`Tactics` != ''))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`User` (
  `NickName` VARCHAR(20) NOT NULL,
  `Name` VARCHAR(20) NULL,
  `LastName` VARCHAR(20) NULL,
  `CurrentRating` INT NOT NULL,
  `idCountry` INT NULL,
  `idPlatform` INT NOT NULL,
  `Rank` ENUM('CM', 'FM', 'IM', 'GM') NULL,
  PRIMARY KEY (`NickName`, `idPlatform`),
  INDEX `fk_User_Country1_idx` (`idCountry` ASC) ,
  INDEX `fk_User_Platform1_idx` (`idPlatform` ASC) ,
  CONSTRAINT `fk_User_Country1`
    FOREIGN KEY (`idCountry`)
    REFERENCES `chessdb`.`Country` (`idCountry`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Platform1`
    FOREIGN KEY (`idPlatform`)
    REFERENCES `chessdb`.`Platform` (`idPlatform`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `NickName_empty` CHECK (`NickName` != ''),
  CONSTRAINT `Name_empty` CHECK (`Name` != ''),
  CONSTRAINT `LastName_empty` CHECK (`LastName` != ''),
  CONSTRAINT `CurrentRating_min` CHECK (`CurrentRating` > 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Opening`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Opening` (
  `idOpening` INT AUTO_INCREMENT,
  `Opening` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idOpening`),
  UNIQUE INDEX `OpeningName_UNIQUE` (`Opening` ASC),
  CONSTRAINT `Opening_Empty` CHECK (`Opening` != ''))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Game` (
  `idGame` INT AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Result` ENUM('White', 'Black', 'Draw') NOT NULL,
  `TotalMoveCount` INT UNSIGNED NOT NULL,
  `StartTime` TIME NOT NULL,
  `SecondToAdd` INT UNSIGNED NOT NULL,
  `idOpening` INT NOT NULL,
  `Path` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idGame`),
  INDEX `fk_Game_Opening1_idx` (`idOpening` ASC),
  CONSTRAINT `fk_Game_Opening1`
    FOREIGN KEY (`idOpening`)
    REFERENCES `chessdb`.`Opening` (`idOpening`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `TotalMoveCount_min` CHECK (`TotalMoveCount` > 0),
  CONSTRAINT `StartTime_min` CHECK (`StartTime` > CAST('00:00:00' AS TIME)),
  CONSTRAINT `Path_regexp` CHECK (REGEXP_LIKE(`Path`, '^[0-9a-zA-Z]+$')))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`User_Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`User_Game` (
  `idGame` INT NOT NULL,
  `NickName` VARCHAR(20) NOT NULL,
  `idPlatform` INT NOT NULL,
  `idUser_Game` INT AUTO_INCREMENT,
  INDEX `fk_User_has_Game_Game1_idx` (`idGame` ASC),
  INDEX `fk_User_Game_User1_idx` (`NickName` ASC, `idPlatform` ASC),
  PRIMARY KEY (`idUser_Game`),
  CONSTRAINT `fk_User_has_Game_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `chessdb`.`Game` (`idGame`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Game_User1`
    FOREIGN KEY (`NickName` , `idPlatform`)
    REFERENCES `chessdb`.`User` (`NickName` , `idPlatform`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`User_Game_Properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`User_Game_Properties` (
  `Color` ENUM('White', 'Black') NOT NULL,
  `Rating` INT NOT NULL,
  `idUser_Game` INT NOT NULL,
  INDEX `fk_User_Game_Properties_User_Game1_idx` (`idUser_Game` ASC),
  PRIMARY KEY (`idUser_Game`),
  CONSTRAINT `fk_User_Game_Properties_User_Game1`
    FOREIGN KEY (`idUser_Game`)
    REFERENCES `chessdb`.`User_Game` (`idUser_Game`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Rating_min` CHECK (`Rating` > 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Sequence` (
  `NumberStartMove` INT UNSIGNED NOT NULL,
  `idUser_Game` INT NOT NULL,
  PRIMARY KEY (`NumberStartMove`, `idUser_Game`),
  INDEX `fk_Sequence_User_Game_Properties1_idx` (`idUser_Game` ASC),
  CONSTRAINT `fk_Sequence_User_Game_Properties1`
    FOREIGN KEY (`idUser_Game`)
    REFERENCES `chessdb`.`User_Game_Properties` (`idUser_Game`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `NumberStartMove_min` CHECK (`NumberStartMove` > 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chessdb`.`Sequence_Tactics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chessdb`.`Sequence_Tactics` (
  `NumberStartMove` INT UNSIGNED NOT NULL,
  `idUser_Game` INT NOT NULL,
  `idTactics` INT NOT NULL,
  `MoveCount` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`NumberStartMove`, `idUser_Game`, `idTactics`),
  INDEX `fk_Sequence_has_Tactics_Tactics1_idx` (`idTactics` ASC),
  INDEX `fk_Sequence_has_Tactics_Sequence1_idx` (`NumberStartMove` ASC, `idUser_Game` ASC),
  CONSTRAINT `fk_Sequence_has_Tactics_Sequence1`
    FOREIGN KEY (`NumberStartMove` , `idUser_Game`)
    REFERENCES `chessdb`.`Sequence` (`NumberStartMove` , `idUser_Game`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sequence_has_Tactics_Tactics1`
    FOREIGN KEY (`idTactics`)
    REFERENCES `chessdb`.`Tactics` (`idTactics`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `MoveCount_min` CHECK (`MoveCount` > 0))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;